import type { Metadata } from "next";
import { content } from "@/data/content";

/** Single source of truth for SEO. Change the domain here only. */
export const site = {
  url: "https://yohanesrioirsan.is-a.dev",
  name: "Yohanes Rio Irsan",
  shortName: "yohanesrioirsan",
  title: "Yohanes Rio Irsan · Software Engineer",
  description:
    "A software engineer from Indonesia, building web apps, tools, and things people can use.",
  jobTitle: "Software Engineer",
  locale: "en_US",
  /** Default social preview image (1200×630), generated by `npm run og`. */
  ogImage: { url: "/og.png", width: 1200, height: 630, alt: "Yohanes Rio Irsan, Software Engineer from Indonesia" },
  sameAs: content.socials.map((social) => social.href).filter(Boolean),
} as const;

/** Absolute URL for a site path, e.g. absoluteUrl("/about"). */
export const absoluteUrl = (path = "/") => new URL(path, site.url).toString();

type PageSeo = {
  /** Page title without the site suffix; the root layout template appends " · Yohanes Rio Irsan". */
  title?: string;
  description?: string;
  /** Route path, used for the canonical URL and og:url. */
  path: string;
  /** Local /public path or absolute URL. Falls back to the default social image. */
  image?: { url: string; alt: string; width?: number; height?: number } | null;
  type?: "website" | "article";
  publishedTime?: string;
  tags?: string[];
};

/**
 * Builds complete page metadata. Next.js replaces (not merges) `openGraph`/`twitter`
 * from parent layouts, so every page gets the full set from here.
 */
export function pageMetadata({ title, description = site.description, path, image, type = "website", publishedTime, tags }: PageSeo): Metadata {
  const fullTitle = title ? `${title} · ${site.name}` : site.title;
  const images = [image ?? site.ogImage];
  return {
    ...(title ? { title } : {}),
    description,
    alternates: { canonical: path },
    openGraph: {
      type,
      url: path,
      siteName: site.name,
      locale: site.locale,
      title: fullTitle,
      description,
      images,
      ...(type === "article" ? { publishedTime, authors: [site.url], tags } : {}),
    },
    twitter: { card: "summary_large_image", title: fullTitle, description, images: images.map((i) => i.url) },
  };
}
